In [3]:
num = list(range(1, 6))

In [4]:
num

[1, 2, 3, 4, 5]

In [7]:
num[::2]

[1, 3, 5]

In [8]:
num[0:5:2]

[1, 3, 5]

In [9]:
num[::-1]

[5, 4, 3, 2, 1]

In [1]:
n = list(range(1, 10, -1))

In [2]:
n

[]

In [7]:
n = list(range(10, 1, -1))

In [4]:
n

[10, 9, 8, 7, 6, 5, 4, 3, 2]

In [5]:
n = list(range(10, 1))

In [6]:
n

[]

In [8]:
for i in n[::-1]:
    print(i)

2
3
4
5
6
7
8
9
10


In [9]:
def f(*args, **kwargs):
    print(args)
    print(kwargs)
    
f(1, 2, name='yim', age=22, major='iot')

(1, 2)
{'name': 'yim', 'age': 22, 'major': 'iot'}


In [10]:
name = 'yim'

In [14]:
print('{%-10s}' % name)

{yim       }


In [16]:
print('{:^20}'.format('seohyun'))

      seohyun       


In [20]:
print('{%-10s}' % 'hi')

{hi        }


In [23]:
print('{:=<10s}'.format('hi'))

hi========


In [30]:
print(f'{name:=<10}')

yim=======


In [31]:
f = 1.512e2

In [32]:
f

151.2

In [36]:
x = 1.1 + 3.14j

In [37]:
print(x.real, x.imag)

1.1 3.14


In [38]:
ms = '''hello'''

In [39]:
ms

'hello'

In [40]:
uc = u'\u00dcnic'

In [41]:
uc

'Ünic'

In [43]:
uc = u'\u00dcni'

In [44]:
uc

'Üni'

In [45]:
uc = u'\u00dcnic\u00f6de'

In [46]:
uc

'Ünicöde'

In [47]:
a = True + 4
b = False + 10

In [48]:
print(a)

5


In [49]:
print(b)

10


In [50]:
x = (1 == True)
y = (1 == False)

In [51]:
print(x, y)

True False


In [52]:
import numpy as np

In [55]:
a = np.array([1, 2, 3])

In [56]:
b = np.array(a, copy=True)
c = np.array(a, copy=False)

In [57]:
a[0] = 50

In [59]:
print(b)
print(c)

[1 2 3]
[50  2  3]


In [60]:
sap = np.array(["MMM", "ABT", "ABBV", "ACN", "ACE", "ATVI", "ADBE", "ADT"])

In [61]:
sap[[1, 2, -1]]

array(['ABT', 'ABBV', 'ADT'], dtype='<U4')

In [62]:
sap[[1, 2]]

array(['ABT', 'ABBV'], dtype='<U4')

In [69]:
sap2d = np.reshape(sap, [2, -1])

In [70]:
sap2d

array([['MMM', 'ABT', 'ABBV', 'ACN'],
       ['ACE', 'ATVI', 'ADBE', 'ADT']], dtype='<U4')

In [86]:
print(sap2d)

[['MMM' 'ABT' 'ABBV' 'ACN']
 ['ACE' 'ATVI' 'ADBE' 'ADT']]


In [72]:
sap2d[:, [1]]

array([['ABT'],
       ['ATVI']], dtype='<U4')

In [73]:
sap2d[:, 1]

array(['ABT', 'ATVI'], dtype='<U4')

In [74]:
sap3d = sap.reshape(2, 2, -1)

In [75]:
sap3d

array([[['MMM', 'ABT'],
        ['ABBV', 'ACN']],

       [['ACE', 'ATVI'],
        ['ADBE', 'ADT']]], dtype='<U4')

In [76]:
sap3d[0, ...]

array([['MMM', 'ABT'],
       ['ABBV', 'ACN']], dtype='<U4')

In [83]:
sap3d[:, 0]

array([['MMM', 'ABT'],
       ['ACE', 'ATVI']], dtype='<U4')

In [85]:
sap3d[:, [0]]

array([[['MMM', 'ABT']],

       [['ACE', 'ATVI']]], dtype='<U4')

In [84]:
sap3d[0]

array([['MMM', 'ABT'],
       ['ABBV', 'ACN']], dtype='<U4')

In [90]:
sap3d[..., 0]

array([['MMM', 'ABBV'],
       ['ACE', 'ADBE']], dtype='<U4')

In [91]:
sap3d[0, :, 0]

array(['MMM', 'ABBV'], dtype='<U4')

In [92]:
sap3d[:, :, -1]

array([['ABT', 'ACN'],
       ['ATVI', 'ADT']], dtype='<U4')

In [94]:
sap3d[..., -1]

array([['ABT', 'ACN'],
       ['ATVI', 'ADT']], dtype='<U4')

In [95]:
sap3d[[0], :, 1]

array([['ABT', 'ACN']], dtype='<U4')

In [96]:
sap3d[0, :, 1]

array(['ABT', 'ACN'], dtype='<U4')

In [99]:
sap3d[0, :, [1]]

array([['ABT', 'ACN']], dtype='<U4')

In [102]:
sap3d[..., [0]]

array([[['MMM'],
        ['ABBV']],

       [['ACE'],
        ['ADBE']]], dtype='<U4')

In [103]:
sap3d[..., 0]

array([['MMM', 'ABBV'],
       ['ACE', 'ADBE']], dtype='<U4')

In [100]:
import pandas as pd

In [104]:
inflation = pd.Series((2.2, 3.4, 2.8, 1.6, 2.3, 2.7, 3.4, 3.2, 2.8, 3.8, -0.4, 1.6, 3.2, 2.1, 1.5, 1.5))

In [105]:
inflation.index

RangeIndex(start=0, stop=16, step=1)

In [106]:
inflation.index.values

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [111]:
num_dict = {'one':1, 'two':2, 'three':3}

In [107]:
num = pd.Series(num_dict)

In [108]:
num

one      1
two      2
three    3
dtype: int64

In [109]:
num.values

array([1, 2, 3])

In [112]:
num_dict.values()

dict_values([1, 2, 3])

In [114]:
num.items

<bound method Series.items of one      1
two      2
three    3
dtype: int64>

In [116]:
num_dict.items()

dict_items([('one', 1), ('two', 2), ('three', 3)])

In [118]:
num_dict.keys()

dict_keys(['one', 'two', 'three'])

In [120]:
a = np.nan

In [121]:
a = np.isnan(a)

In [122]:
a

True

In [125]:
sap

array(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ADBE', 'ADT'],
      dtype='<U4')

In [124]:
np.in1d(["MSFT", "MMM", "AAPL"], sap)

array([False,  True, False])

In [126]:
np.in1d(['ADBE', 'ABBV', 'ACE'], sap)

array([ True,  True,  True])

In [128]:
np.intersect1d(["MSFT", "MMM", "AAPL"], sap)

array(['MMM'], dtype='<U4')

In [129]:
np.union1d(["MSFT", "MMM", "AAPL"], sap)

array(['AAPL', 'ABBV', 'ABT', 'ACE', 'ACN', 'ADBE', 'ADT', 'ATVI', 'MMM',
       'MSFT'], dtype='<U4')