In [1]:
import numpy as np
import pandas as pd

In [2]:
# 거꾸로
num = list(range(1, 10))

In [3]:
num[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1]

In [4]:
for i in range(9, 0, -1):
    print(i, end=' ')

9 8 7 6 5 4 3 2 1 

In [5]:
for i in range(1, 10)[::-1]:
    print(i, end=' ')

9 8 7 6 5 4 3 2 1 

In [6]:
for i in reversed(num):
    print(i, end=' ')

9 8 7 6 5 4 3 2 1 

In [7]:
# 리스트 메서드들 (5가지)

In [8]:
## 값 추가

num.append(10)
num

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [9]:
## 리스트 덧붙이기

num.extend([11, 12])
num

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [10]:
## i번째 인덱스에 값 추가

num.insert(0, '0')
num

['0', 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [11]:
## 특정 값 삭제

num.remove('0')
num

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [12]:
## 특정 인덱스값 삭제

del num[-1]
num

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [13]:
# 리스트 값 거꾸로 정렬 (두가지)
car_ages = [0, 9, 4, 8, 7, 20, 19, 1, 6, 15]

In [14]:
car_ages = sorted(car_ages, reverse=True)
car_ages

[20, 19, 15, 9, 8, 7, 6, 4, 1, 0]

In [15]:
car_ages.sort(reverse=True)
car_ages

[20, 19, 15, 9, 8, 7, 6, 4, 1, 0]

In [16]:
# 특정 타입이 맞는지 확인

In [17]:
isinstance(num, list)

True

In [18]:
# mutable & immutable types

In [19]:
# mutable: list, dictionary, user-defined classes

In [20]:
# immutable: tuple, range, int, float, decimal, bool, string

In [21]:
# type 확인

In [22]:
type(num)

list

In [23]:
# 리스트 인덱스 0에서 5까지 stride 2로 출력

In [24]:
num[0:5:2]

[1, 3, 5]

In [25]:
# unpacking list
colors = ['red', 'green', 'blue']

In [26]:
r, g, b = colors
print(r, g, b)

red green blue


In [27]:
print(*colors)

red green blue


In [28]:
## unpacking

In [29]:
high, * others, low = num
print(high, others, low)

1 [2, 3, 4, 5, 6, 7, 8, 9, 10] 11


In [30]:
# packed

In [31]:
packed = r, g, b

In [32]:
# packed type

In [33]:
type(packed)

tuple

In [34]:
# == and is

In [35]:
# == is for

In [36]:
# is is for

In [37]:
# 문자열에 작은 따옴표 붙이기

In [38]:
name = 'yim'

print(repr(name))

'yim'


In [39]:
## int와 문자열에서의 작은 따옴표 함수

In [40]:
print(f'{repr(num[0])} and {repr(name)}')

1 and 'yim'


In [41]:
# static memory allocation 범위

In [42]:
# -5 ~ 256

In [43]:
# list vs str
ex_list = ['h', 'e', 'l', 'l', 'o']
ex_str = 'hello'

In [44]:
print('he' in ex_list)
print('he' in ex_str)

False
True


In [45]:
# enumerate
ex_list

## start with 1

['h', 'e', 'l', 'l', 'o']

In [46]:
for i, letter in enumerate(ex_list, 1):
    print(f'{i}, {letter:3s}', end=' ')

1, h   2, e   3, l   4, l   5, o   

In [47]:
# 예제에서 next() 썼던 iterable

In [48]:
# list, enumerate, generator

In [49]:
# list interator with next()
ex_list

['h', 'e', 'l', 'l', 'o']

In [50]:
list_it = iter(ex_list)
print(next(list_it))

h


In [51]:
# generator에서 값 내주기 위해 썼던 키워드

In [52]:
def test_gen():
    yield 1
    yield 2
    
gen = test_gen()
print(next(gen))

1


In [53]:
# arguments 종류

In [54]:
# keyword, default, variable-length(unpacking), keyword variable-length

In [55]:
# variable length로 다 더하는 함수 작성

In [56]:
def summation(a, b, *args):
    print(a + b + sum(args))
    
summation(1, 2, 3, 4, 5)

15


In [57]:
# keyword variable-length
## 매개변수를 딕셔너리로
## 딕셔너리를 전달

In [58]:
def f(**kwargs):
    print(['one'])

f(one=1, two=2, three=3)

['one']


In [59]:
def f(**kwargs):
    print(['one'])
    
ex_dic = {'one':1, 'two':2, 'three':3}
f(**ex_dic)

['one']


In [60]:
## args + kwargs

In [61]:
def f(*args, **kwargs):
    print(args)
    print(kwargs)
    
f(10, 20, one=1, two=2, three=3)

(10, 20)
{'one': 1, 'two': 2, 'three': 3}


In [62]:
# type annotation

In [63]:
def say_name(name: str) -> str:
    print(name)
    
say_name('yimethan')

yimethan


In [64]:
# string manipulation

In [65]:
ex_str = '   one two three / four five six '

In [66]:
ex_str.strip()

'one two three / four five six'

In [67]:
ex_str.split()

['one', 'two', 'three', '/', 'four', 'five', 'six']

In [68]:
ex_str.split('/')

['   one two three ', ' four five six ']

In [69]:
# formatting

In [70]:
## (3) 10칸, 0으로 채우기, 오른쪽 정렬 // ('o') 또는 (2) 5칸, =으로 채우거나 채우지 않음, 왼쪽 정렬

In [71]:
print('%010d %-5s' % (3, 'o'))

0000000003 o    


In [72]:
print('{:0>10d}{:=<5s}'.format(3, 'o'))

0000000003o====


In [73]:
print(f'{3:0>10}{2:=<5}')

00000000032====


In [74]:
# literals

In [75]:
## numeric
### binary
### decimal
### octal
### hexadecimal

In [76]:
a = 0b1010
b = 100
c = 0o310
d = 0x12c

In [77]:
print(a, b, c, d)

10 100 200 300


In [78]:
## complex literals

In [79]:
x = 1.5 + 3.14j
print(x, x.real, x.imag)

(1.5+3.14j) 1.5 3.14


In [80]:
## string literals
### multiline string
### unicode

In [81]:
multiline = '''hi
this is
                multiline'''
uc = u'\u00dcnic\u00f6de'
print(multiline)
print(uc)

hi
this is
                multiline
Ünicöde


In [82]:
## boolean literals
### print(1 == True)
### print(True + 4)

In [83]:
print(1 == True)
print(True + 4)

True
5


In [84]:
# conda 가상환경 만들기

In [85]:
% conda create -n name python=3.10

UsageError: Line magic function `%` not found.


In [86]:
% conda activate name
% conda deactivate name

UsageError: Line magic function `%` not found.


In [87]:
# 넘파이 array 생성 (1에서 10까지 1 간격으로)

In [88]:
a = np.array(range(1, 5, 1), copy=True)
a

array([1, 2, 3, 4])

In [89]:
a = np.arange(1, 5, 1)
a

array([1, 2, 3, 4])

In [90]:
## 0, 1로 이뤄진 넘파이
## 빈 어레이

In [91]:
np_ones = np.ones([2, 4])
np_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [92]:
np_zeros = np.zeros([2, 4])
np_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [93]:
np_empty = np.empty([2, 4])
np_empty

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [94]:
# 넘파이 생성 시 dtype 설정

In [95]:
new = np.array([1, 2, 3], dtype=np.float64)
new

array([1., 2., 3.])

In [96]:
# np array 모양 / 차원 / 크기 / 데이터타입 확인

In [97]:
print(new.shape)
print(np_ones.shape)

(3,)
(2, 4)


In [98]:
print(new.ndim)
print(np_ones.ndim)

1
2


In [99]:
print(new.size)
print(np_ones.size)

3
8


In [100]:
print(new.dtype)
print(np_ones.dtype)

float64
float64


In [101]:
### 차원 확인한 결과와 같은 것

In [102]:
print(len(new.shape))

1


In [103]:
# 단위행렬

In [104]:
np_eye = np.eye(3, k=1)
np_eye

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [105]:
# np array 타입 변환

In [106]:
np_eye.astype(int)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [107]:
# list + list vs np + np

In [108]:
print(num + num)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [109]:
print(a + a)

[2 4 6 8]


In [110]:
# copy

In [111]:
a1 = np.array([1, 2, 3])
a2 = np.array(a1, copy=False)
a3 = np.array(a1, copy=True)

a1[0] = 50
print(a1)
print(a2)
print(a3)

[50  2  3]
[50  2  3]
[1 2 3]


In [112]:
# np array shallow copy & deep copy
list_for_np = [1, 'm', [2, 3, 4]]

In [113]:
## shallow copy

In [114]:
a1 = np.array(list_for_np)
a2 = np.array(a1, copy=True)

a1[2][0] = 50

print(a1)
print(a2)

[1 'm' list([50, 3, 4])]
[1 'm' list([50, 3, 4])]


/var/folders/yr/jd3hph_53llgn3rcd194plzc0000gp/T/ipykernel_74060/358520699.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a1 = np.array(list_for_np)


In [115]:
## deep copy

In [116]:
import copy

a1 = np.array(list_for_np)
a3 = copy.deepcopy(a1)

a1[2][0] = 10

print(a1)
print(a3)

[1 'm' list([10, 3, 4])]
[1 'm' list([50, 3, 4])]


/var/folders/yr/jd3hph_53llgn3rcd194plzc0000gp/T/ipykernel_74060/3806708950.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a1 = np.array(list_for_np)


In [117]:
# 넘파이 어레이 크기/차원 바꾸기
sap = np.array(["MMM", "ABT", "ABBV", "ACN", "ACE", "ATVI", "ADBE", "ADT"])

In [118]:
## 2 * 4 행렬로 바꿔 2차원으로 만들기 (2가지 방법)

In [119]:
sap2d = np.reshape(sap, [2, -1])
sap2d

array([['MMM', 'ABT', 'ABBV', 'ACN'],
       ['ACE', 'ATVI', 'ADBE', 'ADT']], dtype='<U4')

In [120]:
sap2d = sap2d.reshape(2, -1)
sap2d

array([['MMM', 'ABT', 'ABBV', 'ACN'],
       ['ACE', 'ATVI', 'ADBE', 'ADT']], dtype='<U4')

In [121]:
# 행과 열 바꾸기
sap3d = sap.reshape(2, 2, 2)
sap3d

array([[['MMM', 'ABT'],
        ['ABBV', 'ACN']],

       [['ACE', 'ATVI'],
        ['ADBE', 'ADT']]], dtype='<U4')

In [122]:
sap3d.swapaxes(1, 2)

array([[['MMM', 'ABBV'],
        ['ABT', 'ACN']],

       [['ACE', 'ADBE'],
        ['ATVI', 'ADT']]], dtype='<U4')

In [123]:
# 전치행렬

In [124]:
sap2d.T

array([['MMM', 'ACE'],
       ['ABT', 'ATVI'],
       ['ABBV', 'ADBE'],
       ['ACN', 'ADT']], dtype='<U4')

In [125]:
# 조건 인덱싱 : 음수 여부 알아내고, 음수인 값 0으로 바꾸기
dirty = np.array([9, 4, 1, -0.01, -0.02, -0.001])

In [126]:
is_dirty = dirty < 0
print(is_dirty)

dirty[is_dirty] = 0
dirty

[False False False  True  True  True]


array([9., 4., 1., 0., 0., 0.])

In [127]:
# 넘파이 조건부

In [128]:
wh = np.where(dirty == 0, 'zero', 'nonzero')
wh

array(['nonzero', 'nonzero', 'nonzero', 'zero', 'zero', 'zero'],
      dtype='<U7')

In [129]:
# 인덱스 1, 2, -1에 해당하는 값으로 새로운 어레이 생성

In [130]:
dirty[[1, 2, -1]]

array([4., 1., 0.])

In [131]:
# 넘파이 2차원 & 3차원 슬라이싱 : 왼쪽 정답 & 오른쪽 정답 번갈아가면서 해 보기
sap2d

array([['MMM', 'ABT', 'ABBV', 'ACN'],
       ['ACE', 'ATVI', 'ADBE', 'ADT']], dtype='<U4')

In [132]:
sap2d[0, 1]

'ABT'

In [133]:
sap2d[[0], :]

array([['MMM', 'ABT', 'ABBV', 'ACN']], dtype='<U4')

In [134]:
sap2d[:, -1]

array(['ACN', 'ADT'], dtype='<U4')

In [135]:
sap2d[-1, [0]]

array(['ACE'], dtype='<U4')

In [136]:
sap2d[[0, 1], [-1, 1]]

array(['ACN', 'ATVI'], dtype='<U4')

In [137]:
sap2d[:, [1]]

array([['ABT'],
       ['ATVI']], dtype='<U4')

In [138]:
sap3d

array([[['MMM', 'ABT'],
        ['ABBV', 'ACN']],

       [['ACE', 'ATVI'],
        ['ADBE', 'ADT']]], dtype='<U4')

In [139]:
sap3d[0, ...]

array([['MMM', 'ABT'],
       ['ABBV', 'ACN']], dtype='<U4')

In [140]:
sap3d[..., 0]

array([['MMM', 'ABBV'],
       ['ACE', 'ADBE']], dtype='<U4')

In [141]:
sap3d[0, -1, 1]

'ACN'

In [142]:
sap3d[:, 1, 0]

array(['ABBV', 'ADBE'], dtype='<U4')

In [143]:
sap3d[..., [0]]

array([[['MMM'],
        ['ABBV']],

       [['ACE'],
        ['ADBE']]], dtype='<U4')

In [144]:
sap3d[[1, 0], 0]

array([['ACE', 'ATVI'],
       ['MMM', 'ABT']], dtype='<U4')

In [145]:
sap3d[:, [0, 1], [0, 1]]

array([['MMM', 'ACN'],
       ['ACE', 'ADT']], dtype='<U4')

In [146]:
sap3d[[0, 1], [0, 1], [0, 1]]

array(['MMM', 'ADT'], dtype='<U4')

In [147]:
sap3d[..., [1, 1]]

array([[['ABT', 'ABT'],
        ['ACN', 'ACN']],

       [['ATVI', 'ATVI'],
        ['ADT', 'ADT']]], dtype='<U4')

In [148]:
# not a number

In [149]:
a = np.nan

In [150]:
a = np.isnan(a)
a

True

In [151]:
# Series 생성
## 튜플로
## 딕셔너리로

In [152]:
inflation = pd.Series((2.2, 3.4, 2.8, 1.6, 2.3, 2.7, 3.4, 3.2, 2.8, 3.8, -0.4, 1.6, 3.2, 2.1, 1.5, 1.5))
inflation

0     2.2
1     3.4
2     2.8
3     1.6
4     2.3
5     2.7
6     3.4
7     3.2
8     2.8
9     3.8
10   -0.4
11    1.6
12    3.2
13    2.1
14    1.5
15    1.5
dtype: float64

In [153]:
num_pd = pd.Series({'one':1, 'two':2, 'three':3})
num_pd

one      1
two      2
three    3
dtype: int64

In [154]:
## Seriees 인덱스와 인덱스 값 확인 & 설정

In [155]:
print(inflation.index)
inflation.index = pd.Index(range(1999, 2015))
print(inflation.index)

RangeIndex(start=0, stop=16, step=1)
RangeIndex(start=1999, stop=2015, step=1)


In [156]:
inflation.index.values

array([1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014])

In [157]:
## Series와 인덱스에 이름 붙이기

In [158]:
inflation.index.name = 'Year'
inflation.name = 'Inflation rate'
inflation

Year
1999    2.2
2000    3.4
2001    2.8
2002    1.6
2003    2.3
2004    2.7
2005    3.4
2006    3.2
2007    2.8
2008    3.8
2009   -0.4
2010    1.6
2011    3.2
2012    2.1
2013    1.5
2014    1.5
Name: Inflation rate, dtype: float64

In [159]:
inflation.columns = ['%']
inflation

Year
1999    2.2
2000    3.4
2001    2.8
2002    1.6
2003    2.3
2004    2.7
2005    3.4
2006    3.2
2007    2.8
2008    3.8
2009   -0.4
2010    1.6
2011    3.2
2012    2.1
2013    1.5
2014    1.5
Name: Inflation rate, dtype: float64

In [160]:
# 앞뒤 5개만 확인하기

In [161]:
inflation.head()

Year
1999    2.2
2000    3.4
2001    2.8
2002    1.6
2003    2.3
Name: Inflation rate, dtype: float64

In [162]:
inflation.tail()

Year
2010    1.6
2011    3.2
2012    2.1
2013    1.5
2014    1.5
Name: Inflation rate, dtype: float64

In [163]:
# 판다스 vs 딕셔너리
num_pd = pd.Series({'one':1, 'two':2, 'three':3})
num_dict = {'one':1, 'two':2, 'three':3}

In [164]:
print(num_pd.values)
print(num_dict.values())

[1 2 3]
dict_values([1, 2, 3])


In [165]:
print(num_pd.items)
print(num_dict.items())

<bound method Series.items of one      1
two      2
three    3
dtype: int64>
dict_items([('one', 1), ('two', 2), ('three', 3)])


In [166]:
print(num_pd.keys)
print(num_dict.keys())

<bound method Series.keys of one      1
two      2
three    3
dtype: int64>
dict_keys(['one', 'two', 'three'])


In [167]:
# 배열을 집합처럼
dna = "AGTCCGCGAATACAGGCTCGGT"

In [168]:
dna_as_array = np.array(list(dna))
dna_set = np.unique(dna_as_array)
dna_set

array(['A', 'C', 'G', 'T'], dtype='<U1')

In [169]:
## np 요소 존재여부 확인 : ["MSFT", "MMM", "AAPL"] 의 값들이 sap에 존재하는지 확인

In [170]:
np.in1d(["MSFT", "MMM", "AAPL"], sap)

array([False,  True, False])

In [171]:
## ["MSFT", "MMM", "AAPL"]의 교집합

In [172]:
np.intersect1d(["MSFT", "MMM", "AAPL"], sap)

array(['MMM'], dtype='<U4')

In [173]:
## ["MSFT", "MMM", "AAPL"]와 sap의 합집합

In [174]:
np.union1d(["MSFT", "MMM", "AAPL"], sap)

array(['AAPL', 'ABBV', 'ABT', 'ACE', 'ACN', 'ADBE', 'ADT', 'ATVI', 'MMM',
       'MSFT'], dtype='<U4')

In [175]:
# LAB

In [176]:
## 섭씨 -> 화씨 온도 : 섭씨 * 1.8 + 32, 2 = 화씨

In [177]:
print('본 프로그램은 섭씨온도를 화씨온도로 변환하는 프로그램입니다.')
c = float(input('변환하고 싶은 섭씨 온도를 입력하세요:'))

print('섭씨온도:', c)
print('화씨온도:', round(c * 1.8 + 32, 2))

본 프로그램은 섭씨온도를 화씨온도로 변환하는 프로그램입니다.
섭씨온도: 5.0
화씨온도: 41.0


In [178]:
## 문자열 역순 출력
### 그냥
### 함수 내 구현

In [179]:
sentence = 'I love you'

for char in reversed(sentence):
    print(char, end='')

uoy evol I

In [180]:
def backwards(word):
    for char in reversed(word):
        print(char)

backwards("SCH university")

y
t
i
s
r
e
v
i
n
u
 
H
C
S


In [181]:
## 야구게임
### 그냥
### 함수 내 구현

In [182]:
num_a = "123"
num_b = "231"

strike = 0
ball = 0

for i in range(3):
    if num_a[i] == num_b[i]:
        strike += 1
    elif num_a[i] in num_b:
        ball += 1
        
print(f"{strike}S {ball}B")

# what is yagu game
# strike: 숫자랑 자리 다 맞을 떼
# ball: 숫자는 맞는데 자리가 틀릴 때

0S 3B


In [183]:
num_a = "123"
num_b = "231"

def game(num_a, num_b):
    strike = 0
    ball = 0

    for i in range(3):
        if num_a[i] == num_b[i]:
            strike += 1
        elif num_a[i] in num_b:
            ball += 1
    
    return strike, ball

s, b = game(num_a, num_b)

print(f"{s}S {b}B")

0S 3B


In [184]:
# 서로소 여부
## 그냥
## 함수 내 구현

In [185]:
a, b = map(int, input().split())

gcd = 0

for i in range(a, 1, -1):
    if b % i == 0 and a % i == 0:
        gcd = i
        break

if gcd == 0:
    print(f'{a} and {b} are coprime.')
else:
    print(f'{a} and {b} are not coprime. GCD is {gcd}.')

5 and 7 are coprime.


In [187]:
def coprime(a, b):
    
    gcd = 0
    
    for i in range(a, 1, -1):
        if a % i == 0 and b % i == 0:
            gcd = i
    
    return gcd

a = int(input("Enter a number: "))
b = int(input("Enter a number: "))

res = coprime(a, b)

if res == 0:
    print(f'{a} and {b} are coprime.')
else:
    print(f'{a} and {b} are not coprime. GCD is {res}.')

5 and 7 are coprime.


In [188]:
## global

In [189]:
def f():
    global s
    s = 'I love London!'
    print(s)
    
s = "I love Paris!"
f()
print(s)

I love London!
I love London!


In [190]:
## 팩토리얼

In [191]:
def factorial(n):
    if n == 1:
        return 1
    else:
        return n*factorial(n-1)

for i in range(1,10):
    print(factorial(i))

1
2
6
24
120
720
5040
40320
362880


In [192]:
## 피보나치 수열
### 재귀
### 메모이제이션
### 태뷸레이션

In [193]:
def fib_rec(n):
    if n == 1 or n == 2:
        return 1
    else:
        return fib_rec(n-1) + fib_rec(n-2)

print(fib_rec(20))

6765


In [194]:
arr = [0]*100

def fib_memo(n):
    # There is a value in the array -> return
    if arr[n-1] != 0:
        return arr[n-1]
    # There is no value in the array -> calculate and save
    else:
        if n == 1 or n == 2:
            result = 1
            arr[n-1] = result
            return result
        else:
            result = fib_memo(n-1) + fib_memo(n-2)
            arr[n-1] = result
            return result
        
print(fib_memo(20))    

6765


In [195]:
def fib_tab(n):
    arr = []
    for i in range(n):
        if i == 0 or i == 1:
            arr.append(1)
        else:
            arr.append(arr[i-1] + arr[i-2])
    return arr[n-1]

print(fib_tab(20))

6765


In [196]:
# 단어 세기

In [197]:
filename = 'yesterday.txt'

target_url = 'https://raw.githubusercontent.com/crazytb/schadvmachinelearning/main/'
target_url = target_url + filename

In [203]:
import urllib
lyric = urllib.request.urlopen(target_url).read()
print(lyric)

b"Yesterday\r\nAll my troubles seemed so far away\r\nNow it looks as though they're here to stay\r\nOh, I believe in yesterday\r\nSuddenly\r\nI'm not half the man I used to be\r\nThere's a shadow hanging over me\r\nOh, yesterday came suddenly\r\nWhy she had to go\r\nI don't know, she wouldn't say\r\nI said something wrong\r\nNow I long for yesterday\r\nYesterday\r\nLove was such an easy game to play\r\nNow I need a place to hide away\r\nOh, I believe in yesterday\r\nWhy she had to go\r\nI don't know, she wouldn't say\r\nI said something wrong\r\nNow I long for yesterday\r\nYesterday\r\nLove was such an easy game to play\r\nNow I need a place to hide away\r\nOh, I believe in yesterday\r\nMm, mm, mm, mm, mm, mm, mm"


In [199]:
## 파일에 가사 쓰기
## 가사에서 특정 단어 개수 세기
## 가사들 모두 대문자로 변경
## 파일 읽기
### 한 줄만
### 전체
## 파일 읽기
### 한 줄 씩 끝까지

In [200]:
filename = 'yesterday.txt'
lyric_file = open(filename,'wb')
lyric_file.write(lyric)
lyric_file.close()

In [210]:
lyric = str(lyric)
n_of_yesterday = lyric.count("yesterday") + lyric.count("Yesterday") + lyric.count("YESTERDAY")
# n_of_yesterday = lyric.upper().count("YESTERDAY")

In [211]:
lyric_cap = lyric.upper()
n_of_yesterday = lyric_cap.count("YESTERDAY")
print(n_of_yesterday)

9


In [212]:
f = open('yesterday.txt', 'r')
lyric_with_readline = f.readline()
lyric_with_readlines = f.readlines()
f.close()

In [213]:
f = open('yesterday.txt', 'r')
while True:
    line = f.readline()
    if not line:
        break
    print(line)
f.close()

Yesterday

All my troubles seemed so far away

Now it looks as though they're here to stay

Oh, I believe in yesterday

Suddenly

I'm not half the man I used to be

There's a shadow hanging over me

Oh, yesterday came suddenly

Why she had to go

I don't know, she wouldn't say

I said something wrong

Now I long for yesterday

Yesterday

Love was such an easy game to play

Now I need a place to hide away

Oh, I believe in yesterday

Why she had to go

I don't know, she wouldn't say

I said something wrong

Now I long for yesterday

Yesterday

Love was such an easy game to play

Now I need a place to hide away

Oh, I believe in yesterday

Mm, mm, mm, mm, mm, mm, mm


In [214]:
## 랜덤으로 숫자 하나 고르기

In [208]:
import random
answer_num = random.randint(1, 100)

In [ ]:
## weird calculator

In [206]:
def weird_calculator(a, b):
    print(f'Addition: {a} + {b}')
    yield a + b
    
    print(f'Subtraction: {a} - {b}')
    yield a - b
    
    print(f'Multiplication: {a} * {b}')
    yield a * b
    
    print(f'Division: {a} / {b}')
    yield a / b
    
a = 10
b = 5
g = weird_calculator(a, b)
print(type(g))

print(next(g))

<class 'generator'>
Addition: 10 + 5
15


In [207]:
# this code into walrus

a = [1, 2, 3, 4, 5, 6]
n = len(a)
if n > 5:
    print(f"List is too long ({n} elements, expected <= 5)")

List is too long (6 elements, expected <= 5)


In [205]:
a = [1, 2, 3, 4, 5, 6]
if (n := len(a)) > 5:
    print(f"List is too long ({n} elements, expected <= 5)")

List is too long (6 elements, expected <= 5)
